services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      ENV_FILE: .env.production
      DOCKERIZED: "1"
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 4
      --timeout 60
      --access-logfile -
      --error-logfile -

  nginx:
    image: nginx:alpine
    container_name: nexus_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - nexus_network
